window.chairmanCases = [
  {
    id: "CASE-001",
    title: "蜘蛛鳥怨念事件",
    level: "黃燈警戒",
    summary: "因前一日晚間適逢人類母親電視劇時段，董事長未能如期出籠巡園。隔日返家後，董事長於籠頂啟動蜘蛛鳥模式，進行翻跟斗、攀爬、倒掛與啾唧抗議。",
    reaction: "董事長正在進行高空巡查。",
    verdict: "本案判定為放風權益受損後之合理高空巡查。",
    humanReview: "人類不得以電視劇時段壓縮董事長放風權益。",
    improvement: "建立放風時段提醒，避免再次觸發怨念值。",
    stamp: "黃燈警戒",
    stampClass: "stamp-alert",
  },
  {
    id: "CASE-002",
    title: "「掉下來買新的」重大失言案",
    level: "橘燈警戒",
    summary: "人類於董事長進行高空巡查時，發表「掉下來買新的」之不當言論。該語句疑似暗示董事長具有可替換性，嚴重傷害本園最高管理層尊嚴。",
    reaction: "更不爽。",
    verdict: "本董事長為品牌核心資產，不接受替換論。",
    humanReview: "人類列入「不懂珍惜名單」。",
    improvement: "所有人類須重新學習董事長不可替換原則。",
    stamp: "人類需改善",
    stampClass: "stamp-human",
  },
  {
    id: "CASE-003",
    title: "BBBBBBB 抓癢服務事故",
    level: "服務品質異常",
    summary: "董事長接受抓癢服務，但因人類手法不佳、位置錯誤或態度敷衍，導致董事長發出：BBBBBBB。",
    reaction: "董事長回覆：BBBBBBB。",
    verdict: "本董事長對本次抓癢服務品質深感不滿。",
    humanReview: "你到底會不會抓？",
    improvement: "重新抓，直到董事長滿意為止。",
    stamp: "BBBBBBB",
    stampClass: "stamp-bbbbbbb",
  },
  {
    id: "CASE-004",
    title: "人類笑聲引發輿情監測案",
    level: "輿情監測",
    summary: "偵測到人類異常笑聲，疑似正在討論董事長私人行為。",
    reaction: "董事長開始介入並凝望現場。",
    verdict: "本案列入園區輿情監測。",
    humanReview: "人類須說明笑聲來源與討論內容。",
    improvement: "討論董事長私人行為前，請先確認自己是否補栗米。",
    stamp: "本鳥已閱",
    stampClass: "stamp-read",
  },
  {
    id: "CASE-005",
    title: "拒絕配合拍照事件",
    level: "本鳥已閱",
    summary: "董事長保有拒絕低品質拍照與錯誤角度紀錄之權利。",
    reaction: "轉身、凝望或直接不配合。",
    verdict: "董事長可拒絕所有不符合品牌形象標準的拍照要求。",
    humanReview: "拍攝前應確認光線、角度與董事長心情。",
    improvement: "重新申請拍攝許可，並提交栗米作為誠意。",
    stamp: "待補件",
    stampClass: "stamp-pending",
  },
  {
    id: "CASE-006",
    title: "咖灰凝望稽核事件",
    level: "凝望稽核",
    summary: "董事長長時間注視人類，未發出聲音，但已完成內部紀錄。",
    reaction: "安靜凝望，情緒不明。",
    verdict: "沉默不代表通過，可能代表正在建立檔案。",
    humanReview: "人類應主動回想今日是否忘記放風、補栗米或抓癢。",
    improvement: "立即自我檢查，必要時前往人類反省區。",
    stamp: "本鳥已閱",
    stampClass: "stamp-read",
  },
];

window.galleryItems = [
  {
    title: "咖灰的凝望",
    image: "./assets/kahui-chairman-hero-v2.png",
    mode: "凝望稽核模式",
    caption: "董事長正在評估你今天的表現。",
  },
  {
    title: "董事長辦公照",
    image: "./assets/kahui-chairman-office.png",
    mode: "查帳模式",
    caption: "黃燈、報表、印章與海邊辦公室。",
  },
  {
    title: "品牌定型參考",
    image: "./assets/brand-board-v1.png",
    mode: "穩重董事長",
    caption: "後續生成與設計都必須維持同一隻咖灰。",
  },
  {
    title: "恰北北現場",
    image: "./assets/stamp-yellow-alert.svg",
    mode: "恰北北模式",
    caption: "警戒燈亮起時，人類請先自我檢討。",
  },
  {
    title: "抓癢驗收",
    image: "./assets/stamp-bbbbbbb.svg",
    mode: "抓癢驗收模式",
    caption: "服務品質不佳時，BBBBBBB 已代表一切。",
  },
  {
    title: "人類偷拍失敗照",
    image: "./assets/stamp-human-improve.svg",
    mode: "人類需改善",
    caption: "拍攝角度不符標準，請重新申請。",
  },
];
